# CloudFormation's AWS::EC2::KeyPair generates the key material itself and stores the private half in SSM
# Parameter Store at /ec2/keypair/<key-pair-id>. Terraform has no equivalent, so the three resources below
# reproduce it: the key is generated by the tls provider, the public half becomes the key pair, and the private
# half is written to the same parameter path so the same "aws ssm get-parameter" command works.
resource "tls_private_key" "key_pair" {
  algorithm = "RSA"
  rsa_bits  = 4096
}
resource "aws_key_pair" "key_pair" {
  key_name   = var.key_name
  public_key = tls_private_key.key_pair.public_key_openssh
}
resource "aws_ssm_parameter" "key_pair_private_key" {
  name  = "/ec2/keypair/${aws_key_pair.key_pair.key_pair_id}"
  type  = "SecureString"
  value = tls_private_key.key_pair.private_key_pem
}
