output "ebs_csi_driver_addon_arn" {
  value       = aws_eks_addon.ebs_csi_driver.arn
  description = "ARN of the aws-ebs-csi-driver EKS addon"
}
output "role_arn" {
  value       = aws_iam_role.ebs_csi_driver.arn
  description = "ARN of the IAM role the driver's controller assumes through IRSA"
}
output "role_name" {
  value       = aws_iam_role.ebs_csi_driver.name
  description = "Name of the driver's IAM role, generated by AWS when role_name was left null"
}
output "service_account" {
  value       = "${var.namespace}/${var.service_account_name}"
  description = "The namespace/service-account the trust policy is scoped to. Worth surfacing: a mismatch between this and what the addon actually creates leaves every PersistentVolumeClaim Pending with an AccessDenied only in the controller's log"
}
output "volume_check_command" {
  value       = "kubectl get pvc -A && kubectl -n ${var.namespace} logs deploy/ebs-csi-controller -c ebs-plugin --tail 50"
  description = "Command listing every claim and then the controller's log. The first place to look when a Helm release is stuck waiting on pods, and the STORAGECLASS column decides which way to read it: empty means the claim resolved to no class at all and the driver was never asked to do anything, so check kubectl get storageclass rather than this log. A class named but the claim still Pending is the driver failing, usually its IAM role missing AmazonEBSCSIDriverPolicy"
}
