terraform {
  required_version = ">= 1.9"
  required_providers {
    aws     = { source = "hashicorp/aws", version = "~> 6.0" }
    tls     = { source = "hashicorp/tls", version = "~> 4.0" }
    helm    = { source = "hashicorp/helm", version = "~> 3.0" }
    kubectl = { source = "alekc/kubectl", version = "~> 2.4" }
    # Only for one resource, and only because nothing else here can express what it expresses - see the
    # time_sleep in main.tf, which closes a two-second race between a member cluster registering itself and
    # Karmada scheduling the demo workload.
    time = { source = "hashicorp/time", version = "~> 0.12" }
  }
}
provider "aws" {
  region = var.aws_region
}
# ---------------------------------------------------------------------------------------------------------
# What this root builds, and why it looks the way it does
# ---------------------------------------------------------------------------------------------------------
#
# Three EKS clusters in one VPC - a parent carrying the Karmada control plane and two members registered
# with it - plus the demo workload Karmada divides between the members, and a workbench instance to drive
# them from.
#
# All of that used to be built by a shell script. The _monolithic template cloned
# aws-solutions-library-samples/guidance-for-multi-cluster-application-management-with-karmada-and-amazon-eks
# onto the workbench and ran its deploy-karmada-run.sh, which created the clusters with eksctl, installed
# Karmada with `kubectl karmada init`, joined the members with `kubectl karmada join`, and applied the demo
# with kubectl. An earlier version of this configuration kept that shape and ran the same script from an SSM
# Association, documented here as a deliberate exception to rules.md E-1.
#
# It is no longer an exception. Everything the script produced is now a Terraform resource, which is what
# rules.md E-1 asks for, and the difference is not cosmetic:
#
#   terraform plan shows the clusters, the addons, the Karmada release and the propagation policy. Before,
#   it showed one SSM Association whose parameters happened to contain a script.
#
#   terraform destroy removes them. Before, it removed the workbench and left three EKS clusters running,
#   with their own node groups, and the only supported way to remove them was to run the script again with
#   its -d flag and type "iReallyMeanIt" at a prompt.
#
#   a failure is a Terraform error naming a resource. Before, it was "unexpected state 'Failed'" from an
#   SSM Association, with the reason in a log file on an instance (rules.md A-4 has that procedure).
#
# Three pieces of it are not a line-for-line translation, and each one is a decision rather than an
# oversight. They are documented where they are implemented, and summarised here because they are the first
# things a reader comparing this against the script will notice:
#
#   Member registration is Pull, not Push. `karmadactl join` sets up push mode by reading a ServiceAccount
#   token out of the member cluster, which nothing in this provider set can do - see
#   modules/karmada_member_agent. The Cluster objects differ in one column.
#
#   The Karmada API server is published through a load balancer Terraform creates, not one a controller
#   creates in response to a Service. Its address has to be a value here, because the certificate, the
#   agents and the kubectl provider below all need it - see modules/karmada_api_load_balancer.
#
#   The PKI is generated by Terraform rather than inside the cluster, which is what makes the previous point
#   possible and is also why the kubectl provider below can authenticate at all - see
#   modules/karmada_certificates. The CA private key is in Terraform state as a result; treat this state file
#   as a secret.
#
# ---------------------------------------------------------------------------------------------------------
# The provider set
# ---------------------------------------------------------------------------------------------------------
#
# Four clusters' worth of credentials, for three EKS API servers and one Karmada API server. Every provider
# is aliased, including the ones that could be defaults: an unaliased provider is inherited by any module
# that forgets its providers argument, and such a module would then quietly apply to whichever cluster the
# default happened to be. With no default at all, forgetting it is a configuration error instead
# (rules.md I-3 makes the same argument about regions).
#
# All three EKS providers authenticate the way the workbench does after `aws eks update-kubeconfig`: an exec
# credential plugin calling `aws eks get-token`. This is also why every cluster in this root has
# endpoint_public_access on - these providers run wherever terraform runs, which is outside the VPC. The one
# shape where that is not required is rules.md E-9's, and it trades away having any Kubernetes object in
# state.
provider "helm" {
  alias = "parent"
  # Isolates chart resolution from whatever Helm state exists on the machine running Terraform. Without
  # these the provider uses Helm's own repositories.yaml and index cache, and a leftover named repository
  # whose URL matches chart_repository makes the plan fail with "no cached repo found. (try 'helm repo
  # update')".
  #
  # A cache directory per provider, not one shared between them, and here that is not a precaution: all
  # three providers below install the same chart from the same repository, so with one cache they race to
  # download it. Each writes a temporary file and renames it into place, and the second rename fails because
  # the first provider still holds the target. On Windows that surfaces during plan as
  #
  #   Error: Error locating chart
  #   Unable to locate chart karmada: link error: cannot rename ...karmada-v1.19.0.tgz3335701678 to
  #   ...tgz: Access is denied.
  #
  # which reads like a missing chart rather than three writers. The duplicate download is the cost.
  repository_config_path = "${path.root}/.terraform/helm/parent/repositories.yaml"
  repository_cache       = "${path.root}/.terraform/helm/parent/cache"

  kubernetes = {
    host                   = module.parent_eks_cluster.cluster_endpoint
    cluster_ca_certificate = base64decode(module.parent_eks_cluster.certificate_authority_data)
    exec = {
      api_version = "client.authentication.k8s.io/v1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", module.parent_eks_cluster.cluster_name]
    }
  }
}
provider "helm" {
  alias = "member_1"

  repository_config_path = "${path.root}/.terraform/helm/member_1/repositories.yaml"
  repository_cache       = "${path.root}/.terraform/helm/member_1/cache"

  kubernetes = {
    host                   = module.member_1_eks_cluster.cluster_endpoint
    cluster_ca_certificate = base64decode(module.member_1_eks_cluster.certificate_authority_data)
    exec = {
      api_version = "client.authentication.k8s.io/v1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", module.member_1_eks_cluster.cluster_name]
    }
  }
}
provider "helm" {
  alias = "member_2"

  repository_config_path = "${path.root}/.terraform/helm/member_2/repositories.yaml"
  repository_cache       = "${path.root}/.terraform/helm/member_2/cache"

  kubernetes = {
    host                   = module.member_2_eks_cluster.cluster_endpoint
    cluster_ca_certificate = base64decode(module.member_2_eks_cluster.certificate_authority_data)
    exec = {
      api_version = "client.authentication.k8s.io/v1"
      command     = "aws"
      args        = ["eks", "get-token", "--cluster-name", module.member_2_eks_cluster.cluster_name]
    }
  }
}
# alekc/kubectl rather than hashicorp/kubernetes, for both of the reasons rules.md E-2 gives.
#
# The parent cluster is created in this same apply, so its endpoint is unknown while Terraform is
# configuring providers during plan - hashicorp/kubernetes fails there with "Failed to construct REST client
# ... no client config". lazy_load defers building the client until a resource is first used, which is
# during apply, after the cluster exists.
#
# And the objects applied through these providers include a PropagationPolicy, a custom resource whose CRD
# is installed by a Helm release in this same apply - a schema hashicorp/kubernetes would need to resolve at
# plan time and cannot (rules.md E-3).
provider "kubectl" {
  alias                  = "parent"
  host                   = module.parent_eks_cluster.cluster_endpoint
  cluster_ca_certificate = base64decode(module.parent_eks_cluster.certificate_authority_data)
  load_config_file       = false
  lazy_load              = true
  exec {
    api_version = "client.authentication.k8s.io/v1"
    command     = "aws"
    args        = ["eks", "get-token", "--cluster-name", module.parent_eks_cluster.cluster_name]
  }
}
# The Karmada API server, which is the provider this whole configuration is arranged around. It is not an
# EKS cluster and `aws eks get-token` means nothing to it: it is a kube-apiserver whose only authentication
# is the client certificate modules/karmada_certificates generated, presented over the load balancer
# modules/karmada_api_load_balancer created.
#
# Three things have to be true for it to work, and all three are the subject of a module comment rather than
# an accident:
#
#   the certificate's Organization includes system:masters, or it authenticates and can read nothing;
#   the certificate carries the load balancer's DNS name as a SAN, or the TLS handshake fails;
#   the load balancer is internet-facing, because this provider runs outside the VPC.
provider "kubectl" {
  alias = "karmada"
  host  = module.karmada_api_load_balancer.endpoint
  # Already PEM, unlike the EKS providers above - those get base64 from the AWS API, this comes from the tls
  # provider.
  cluster_ca_certificate = module.karmada_certificates.ca_cert_pem
  client_certificate     = module.karmada_certificates.cert_pem
  client_key             = module.karmada_certificates.private_key_pem
  load_config_file       = false
  lazy_load              = true
  # Cheap insurance on a race that should not happen. The demo workload applies after the control plane's
  # Helm release has finished, and by then the load balancer's targets have been healthy for minutes:
  # kube-proxy opens the node port as soon as the Service object exists, which is early in the release,
  # while helm goes on waiting for an EBS volume to be provisioned and for the CRD job to finish. The margin
  # is large, but it is a margin rather than a signal - nothing here can observe target health - so a
  # couple of retries cover the case where it is not.
  apply_retry_count = var.karmada_apply_retry_count
}
