# The _monolithic template installed the Vertical Pod Autoscaler by cloning
# kubernetes/autoscaler onto the bastion and running hack/vpa-up.sh from an SSM
# Association, after separately applying vpa-v1-crd-gen.yaml and vpa-rbac.yaml. That
# script applies the CRD, the RBAC, three Deployments and a self-signed webhook
# certificate; none of it was tracked, the version was whatever the default branch
# held that day, and a second run was not reliably idempotent.
#
# This is the same software as a pinned chart (rules.md E-1). The CRD ships in the
# chart's crds/ directory, so helm installs it before the templates - which is what
# vpa-up.sh's ordering was for - and the webhook certificate is generated by a
# pre-install hook Job instead of by openssl in a shell script.
#
# hashicorp/helm needs no cluster access at plan time, so this works in the same
# apply that creates the cluster and does not need the alekc/kubectl workaround
# (rules.md E-2).
resource "helm_release" "vertical_pod_autoscaler" {
  name             = var.release_name
  repository       = var.chart_repository
  chart            = "vpa"
  version          = var.chart_version
  namespace        = var.namespace
  create_namespace = var.create_namespace
  # Holds the apply until the three Deployments are Available and the certificate
  # hook has finished. Without it the hamster workload's VerticalPodAutoscaler could
  # be created before the CRD's webhook is serving, and the admission controller
  # would miss the first pods.
  wait    = true
  timeout = var.timeout_seconds
  set = concat([
    {
      name  = "recommender.enabled"
      value = tostring(var.recommender_enabled)
    },
    {
      name  = "updater.enabled"
      value = tostring(var.updater_enabled)
    },
    {
      name  = "admissionController.enabled"
      value = tostring(var.admission_controller_enabled)
    },
    # The chart can bring its own metrics-server as a subchart. Left off because
    # metrics-server is an EKS addon here, and two of them contend for the same
    # v1beta1.metrics.k8s.io APIService.
    {
      name  = "metrics-server.enabled"
      value = tostring(var.install_metrics_server)
    },
    ],
    var.additional_set_values,
  )
}
