variable "release_name" {
  type        = string
  default     = "vpa"
  description = "Helm release name. Also the prefix for the admission controller's Service and TLS secret, so it appears in the webhook configuration"
  validation {
    condition     = can(regex("^[a-z0-9]([-a-z0-9]*[a-z0-9])?$", var.release_name))
    error_message = "release_name must be a valid lowercase RFC 1123 DNS label."
  }
}
variable "chart_repository" {
  type        = string
  default     = "https://charts.fairwinds.com/stable"
  description = "Chart repository URL. The Fairwinds chart is the packaged form of the upstream vertical-pod-autoscaler: the _monolithic template cloned kubernetes/autoscaler and ran hack/vpa-up.sh, which is a shell script that applies the CRD, the RBAC and three Deployments and generates the webhook certificate - none of it tracked, and re-runnable only by luck"
  validation {
    condition     = can(regex("^(https?|oci)://", var.chart_repository))
    error_message = "chart_repository must be an http(s) or oci URL."
  }
}
variable "chart_version" {
  type        = string
  default     = "5.1.0"
  description = "Chart version, pinned. The _monolithic template cloned the autoscaler repository's default branch, so the VPA it installed changed as upstream moved and nothing recorded which version was in the cluster"
  validation {
    condition     = can(regex("^[0-9]+\\.[0-9]+\\.[0-9]+", var.chart_version))
    error_message = "chart_version must be a semver version, e.g. 5.1.0."
  }
}
variable "namespace" {
  type        = string
  default     = "vpa"
  description = "Namespace the VPA components run in. A namespace of their own rather than kube-system: vpa-up.sh puts them in kube-system, but nothing requires it, and separating them makes it obvious which pods belong to this project"
  validation {
    condition     = can(regex("^[a-z0-9]([-a-z0-9]*[a-z0-9])?$", var.namespace))
    error_message = "namespace must be a valid lowercase RFC 1123 DNS label."
  }
}
variable "create_namespace" {
  type        = bool
  default     = true
  description = "Whether helm creates the namespace. True, because the namespace above does not otherwise exist"
}
variable "timeout_seconds" {
  type        = number
  default     = 900
  description = "How long helm waits for the release to become ready. Generous because the admission controller's certificate is generated by a pre-install hook Job, and the release is not ready until that has run and the webhook is serving"
  validation {
    condition     = var.timeout_seconds > 0
    error_message = "timeout_seconds must be positive."
  }
}
variable "recommender_enabled" {
  type        = bool
  default     = true
  description = "Whether the recommender runs. The component that watches actual usage and writes the recommendation onto the VerticalPodAutoscaler's status - with it off, a VPA object exists and never gets an opinion"
}
variable "updater_enabled" {
  type        = bool
  default     = true
  description = "Whether the updater runs. The component that evicts pods whose requests are far from the recommendation, which is what makes updateMode Auto or Recreate actually do something. With it off, a VPA in Auto mode behaves like Off"
}
variable "admission_controller_enabled" {
  type        = bool
  default     = true
  description = "Whether the admission controller runs. It rewrites resource requests as pods are created, so it is what applies a recommendation to a replacement pod. Without it the updater would evict pods that then come back with their original requests, which is worse than not scaling at all"
}
variable "install_metrics_server" {
  type        = bool
  default     = false
  description = "Whether the chart installs its bundled metrics-server subchart. False: metrics-server is an EKS addon in this project, and two installations would race to serve the same metrics API endpoint - the one that loses leaves the APIService intermittently unavailable"
}
variable "additional_set_values" {
  type = list(object({
    name  = string
    value = string
    type  = optional(string)
  }))
  default     = []
  description = "Extra helm values appended to the set list. type is auto when omitted, and only auto or string are accepted - a caller with no way to force a string could not pass an annotation value (rules.md E-7)"
  validation {
    condition     = alltrue([for entry in var.additional_set_values : entry.type == null || contains(["auto", "string"], entry.type)])
    error_message = "additional_set_values type must be auto or string when set."
  }
}
